src/app/app.module.ts
src/app/components/control-bar/control-bar.component.html
src/app/components/control-bar/control-bar.component.ts
src/app/components/modal-current-project/modal-current-project.component.html
src/app/components/modal-current-project/modal-current-project.component.scss
src/app/components/modal-current-project/modal-current-project.component.spec.ts
src/app/components/modal-current-project/modal-current-project.component.ts
src/app/components/modal-file-browser/modal-file-browser.component.ts
src/app/services/projects.service.ts

I have added a feature where you can see your current project name & description. You can also edit and update them. I have added the deletion button for the current project but it's a little dangerous since it can delete shared projects.

current project DEL/UPD

---

src/app/app.module.ts
src/app/components/control-bar/control-bar.component.ts
src/app/components/modal-current-project/modal-current-project.component.ts
src/app/components/modal-download-selector/modal-download-selector.component.ts
src/app/services/tapis-files.service.ts

update delete message to be a bit more informative.

General improvements to file uploader's UI, and

---

src/app/app.module.ts
src/app/components/control-bar/control-bar.component.html
src/app/components/control-bar/control-bar.component.ts
src/app/components/modal-share-project/modal-share-project.component.html
src/app/components/modal-share-project/modal-share-project.component.scss
src/app/components/modal-share-project/modal-share-project.component.spec.ts
src/app/components/modal-share-project/modal-share-project.component.ts
src/app/models/models.ts
src/app/services/projects.service.ts

Created interface for sharing project and managing

---

src/app/components/side-bar/tag-images/form-generator/form-fields/form-color/form-color.component.ts
src/app/services/forms.service.ts

Basic functions and paths to add a custom icon

---

src/app/components/side-bar/tag-images/form-generator/form-fields/form-color/form-color.component.ts
src/app/services/forms.service.ts

Revert "Basic functions and paths to add a custom icon"

---

src/app/services/forms.service.ts
src/app/services/projects.service.ts

Color data is now saved to the proper image,
Fixed bug in creating new project

Final tweaks to the feature, plus bug fixes

---

package-lock.json
package.json
src/app/components/modal-download-selector/modal-download-selector.component.html
src/app/components/modal-download-selector/modal-download-selector.component.ts
src/app/components/modal-file-browser/modal-file-browser.component.html
src/app/components/modal-file-browser/modal-file-browser.component.ts
src/app/services/tapis-files.service.ts

file browser and download selector now will scroll through
all of the avaliable files!

Fixed issue #2

---

src/app/components/control-bar/control-bar.component.ts
src/app/components/image-box/image-box.component.ts
src/app/components/image-gallery/image-gallery.component.ts
src/app/services/forms.service.ts
src/app/services/geo-data.service.ts
src/app/services/notifications.service.ts
src/app/services/projects.service.ts

Variety of quality of life changes,

---

src/app/components/control-bar/control-bar.component.ts
src/app/components/side-bar/tag-generator/tag-generator.component.ts
src/app/components/side-bar/tag-images/tag-images.component.html
src/app/components/side-bar/tag-images/tag-images.component.ts
src/app/services/forms.service.ts

Group delete also deletes all the tags inside the features

tags and updates are saved in real time 

---

src/app/components/control-bar/control-bar.component.ts
src/app/components/modal-current-project/modal-current-project.component.ts
src/app/services/projects.service.ts

Resloved issue of getting stuck in an empty taggit screen
when creating a new project from the taggit screen

Solved breaking issue

---

src/app/components/control-bar/control-bar.component.ts
src/app/services/feature.service.spec.ts
src/app/services/feature.service.ts

FeatureService abstracts and centeralizes the control of
feature lists and tag lists.

Added new service

---

src/app/components/image-box/image-box.component.ts
src/app/components/side-bar/tag-generator/tag-generator.component.ts
src/app/components/side-bar/tag-images/tag-images.component.html
src/app/components/side-bar/tag-images/tag-images.component.ts
src/app/services/feature.service.ts
src/app/services/forms.service.ts
src/app/services/groups.service.ts

Along side minor tweaks to tag and feature saving

Tag deletion and creation

---

src/app/components/side-bar/tag-generator/tag-generator.component.ts
src/app/services/feature.service.ts

Fixed bug with renaming and deleting tags,
can now resolve 2 tags with the same name
and properly rename or delete them without changes overflowing to
other tags

Minor bug fixes and documentation tweaks

---

src/app/components/control-bar/control-bar.component.html
src/app/components/side-bar/tag-generator/tag-generator.component.ts
src/app/components/side-bar/tag-images/form-generator/form-fields/form-checkbox/form-checkbox.component.ts
src/app/components/side-bar/tag-images/form-generator/form-fields/form-color/form-color.component.ts
src/app/components/side-bar/tag-images/form-generator/form-fields/form-dropdown/form-dropdown.component.ts
src/app/components/side-bar/tag-images/form-generator/form-fields/form-radio/form-radio.component.ts
src/app/components/side-bar/tag-images/form-generator/form-fields/form-textbox/form-textbox.component.ts
src/app/components/side-bar/tag-images/tag-images.component.ts
src/app/services/feature.service.ts
src/app/services/forms.service.ts
src/app/services/projects.service.ts

These solves this [bug](https://github.com/taggit-tacc/taggit/issues/79)

bug fixes for tags and features

---

src/app/app.interceptors.ts
src/app/components/modal-current-project/modal-current-project.component.html
src/app/models/models.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Hide delete button when the project is not delectable.  See  https://github.com/TACC-Cloud/geoapi/pull/100 
Also, this PR adds use of JWT so local `geoapi` service can be used.
* [DES-1996](https://jira.tacc.utexas.edu/browse/DES-1996)
Use related PR https://github.com/TACC-Cloud/geoapi/pull/100 when testing

Task/DES-1996: hide delete button if project is not deletable

---

src/app/components/control-bar/control-bar.component.html
src/app/components/control-bar/control-bar.component.ts
src/app/components/image-box/image-box.component.html
src/app/components/image-box/image-box.component.ts
src/app/components/side-bar/tag-images/form-generator/form-fields/form-color/form-color.component.ts
src/app/models/models.ts
src/app/services/forms.service.ts
src/app/services/geo-data.service.ts
src/app/services/groups.service.ts

Persist select group modal selections.

Persist group menu

---

src/index.html

Added new Google Analytics 4 tracking property MeasurementID for taggit in the base template page.
- [WG-180](https://jira.tacc.utexas.edu/browse/WG-180)
- Changed the GA4 code measurementID value.
1. Build and run project.
2. Verify new GA4 code is in all page templates. 
- None
- None

Taggit PROD GA4 MeasurementID

---

Makefile
src/environments/environment.ts

This PR:
* update Makefile to build latest image
* uses similar commands as geoapi/hazmapper Makefiles

hotfix: update Makefile to build latest image

---

src/app/app.interceptors.ts
src/app/app.module.ts
src/app/components/control-bar/control-bar.component.ts
src/app/services/agave-systems.service.ts
src/app/services/authentication.service.ts
src/app/services/env.service.ts
src/app/services/tapis-files.service.ts
src/environments/environment.ts

This PR:
* Add checks if token is expired and force logout [WG-284](https://tacc-main.atlassian.net/browse/WG-284)
* Configure designsafe URL based on environment  [WG-288](https://tacc-main.atlassian.net/browse/WG-288)
* [WG-284](https://tacc-main.atlassian.net/browse/WG-284)
* [WG-288](https://tacc-main.atlassian.net/browse/WG-288)
1. Confirm you can log in
2. Confirm you can use DS (i.e. get project listings when getting files)

task/WG-284: check if token expires

---

src/app/services/agave-systems.service.ts

Fix system. listings
* [WG-482](https://tacc-main.atlassian.net/browse/WG-482)

task/WG-482: fix system listing

---

src/app/app.component.ts

Remove login in ngOnInit to stop double login from occuring
* [WG-289](https://tacc-main.atlassian.net/browse/WG-289)
1. Login and confirm that you only see tapis login once

task/WG-289: fix double login

---

src/app/app-routing.module.ts
src/app/components/callback/callback.component.ts
src/app/services/authentication.service.ts

Remove query-param approach for auth flow.  Now using hash.
* [WG-493](https://tacc-main.atlassian.net/browse/WG-493)
1. Just a code review is sufficient.

task/WG-493: Remove query-param approach for auth flow

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/callback/callback.component.ts
src/app/components/logout/logout.component.html
src/app/components/logout/logout.component.scss
src/app/components/logout/logout.component.spec.ts
src/app/components/logout/logout.component.ts
src/app/services/authentication.service.ts
src/app/services/env.service.ts
src/environments/environment.ts
src/environments/environmentType.ts
src/index.html

Support hazmapper-tmp in taggit.  
This PR also
* supports deployment at hazmapper-tmp
* switches auth to use geoapi instead of client-side implicit auth 
* [WG-511](https://tacc-main.atlassian.net/browse/WG-511)
1. (deploying to staging for testing)
2. test `https://hazmapper.tacc.utexas.edu/taggit-staging/`. (you can logout via https://hazmapper.tacc.utexas.edu/taggit-staging/logout)

task/WG-511: support hazmapper tmp
